// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/28/2026, 9:39:15 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/mac/Documents/wisekings/merchant/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/merchant/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/merchant/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/merchant/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/merchant/plugins/**/*.{js,ts,mjs}","/Users/mac/Documents/wisekings/merchant/composables/**/*.{js,ts,mjs}","/Users/mac/Documents/wisekings/merchant/utils/**/*.{js,ts,mjs}","/Users/mac/Documents/wisekings/merchant/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/merchant/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/merchant/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/merchant/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;